### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by Jawad-Nazari** [Cisco-the-wayword/TPPS-Conference#2]
**Hi @Cisco-the-wayword ,**

- Well done and a very nice project. 👏  
- Your code looks well-organized and structured.
- I just noticed that the image tags in the addSpeakers function should have an alternative text specified using the alt attribute for better accessibility and it will be great if you consider it next time.

**Comment by Cisco-the-wayword** [comment]
Thank you @Jawad-Nazari 
I have added the changes
